### PR TITLE
OP-958 add equivsbuild and rpmbuild to buildenv

### PR DESCRIPTION
**Pull request by arcolife**
Also, remove build-bnfc as per discussion in #development

WIP

- [x] need to add `bintray_cfg` directory in Dockerfile and change `init-buildenv` accordingly
- [x] Add bintray wrapper script either here, or as a plugin (if completed)

Refactored Dockerfile

Is applicable when:
- COSL is refactored into `packages[].licenses` in `package_config.yaml`

### CODE REVIEW

**Comment by TomVasile** [comment]
seems fine so far

**Comment by arcolife** [comment]
Also removed `init-buildenv` and refactored Dockerfile. 

^because, 1 step failure towards the end of init script costs a lot of time and defeats the purpose of layered builds in Docker.

**Comment by TomVasile** [comment]
please fix for drone before we review

**Comment by arcolife** [comment]
it was behind master. Go ahead now

**Comment by arcolife** [comment]
good to merge 
https://drone-auto.casperlabs.io/arcolife/CasperLabs/71/1/14
https://drone-auto.casperlabs.io/arcolife/CasperLabs/70/1/1

**Comment by TomVasile** [comment]
also why are these binaries needed? 

bintray/gold/casperlabs_0.12.1_all.deb etc

**Comment by arcolife** [comment]
> need to update .drone.yml for building and publishing via the dockerfile

what does this mean? a publish on merge happens and a build happened in CI already

**Comment by arcolife** [comment]
> also why are these binaries needed?
> 
> bintray/gold/casperlabs_0.12.1_all.deb etc

Removed. Must've crept in from the work in `test_bintray` branch when I had a plan to include tests for upload to bintray. 

Will add that in a separate PR

https://drone-auto.casperlabs.io/arcolife/CasperLabs/71/1/14
https://drone-auto.casperlabs.io/arcolife/CasperLabs/70/1/1
^these tests suffice for now.

**Pull request merged**
